{% set name = "Frozen-Flask" %}
{% set version = "1.0.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "86ea01ce8b8a4b2a8cc560cbf9c9f01470072b19162042301b0d97a05bc98add" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower|replace("-", "_") }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip

  run:
    - python >=3.8
    - flask >=2.0.0

test:
  imports:
    - flask_frozen
    - flask_frozen.tests.test_app
    - flask_frozen.tests.test_app.admin

about:
  home: https://github.com/Frozen-Flask/Frozen-Flask
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'Freezes a Flask application into a set of static files.'
  dev_url: https://github.com/Frozen-Flask/Frozen-Flask
  doc_url: https://frozen-flask.readthedocs.io/

extra:
  recipe-maintainers:
    - pmlandwehr
