{% set name = "Frozen-Flask" %}
{% set version = "0.18" %}
{% set bundle = "tar.gz" %}
{% set hash = "4113638baebb348e16b10b12cbd88bddc7309f24d94332a18ae6a56c8ac02d3d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - flask >=0.7

test:
  imports:
    - flask_frozen
    - flask_frozen.test_app
    - flask_frozen.test_app.admin

about:
  home: https://github.com/SimonSapin/Frozen-Flask
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Freezes a Flask application into a set of static files.
  dev_url: https://github.com/SimonSapin/Frozen-Flask
  doc_url: https://pythonhosted.org/Frozen-Flask/

extra:
  recipe-maintainers:
    - pmlandwehr
