{% set name = "Frozen-Flask" %}
{% set version = "1.0.2" %}
{% set bundle = "tar.gz" %}
{% set hash = "53a7895b188b7d59eb8d6fcf3fce18e097d8b4a26b6bb665e176add1a1e03aaf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_').lower() }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python
    - flask >=0.7

test:
  imports:
    - flask_frozen
    - flask_frozen.test_app
    - flask_frozen.test_app.admin

about:
  home: https://github.com/SimonSapin/Frozen-Flask
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'Freezes a Flask application into a set of static files.'
  dev_url: https://github.com/SimonSapin/Frozen-Flask
  doc_url: https://pythonhosted.org/Frozen-Flask/

extra:
  recipe-maintainers:
    - pmlandwehr
