travis:
  secure:
    BINSTAR_TOKEN: PmGTu5T/WDMcPuWbfRT4TNUBv9NkiHxi43ELTxm2Z3bTzmx7VfP/nUVhj6DXV8gPedsU+z8cL0j5t6zFMvZpIBRD7xSIrLLK6XH6VVnA3F65RlRUqII6BvDubcQ0dZfVu2utNe2ZTC40c/x4UocS7lBbegWek5P/XIwFqie244htMg2pQ0WZQgeNqikCixkffEbvSXMKCr6DQAIQ124LDvBtFLuO/QluJe9toLM/4TaUKwXuto6selScEJOAEttR9cvvLvLxMMYIoOQVcY2CsSaTWxCcFZYaMoTfi2BTIu3tt8zwpNNwhRPL07AMjC3UyYZPzCn1IUZIuKyHXY6979Azyp3SdbRS3Of0yKqhfGMvfwhU+dYlHrBUhpOpI2yNqKeOXL7JYXIgdik/1spUpifU6VTqKSjmXp0rpneZjtUPC3xPH4wvM0gYpK57U9aE/rFGxlyj9ZfWLVPaNU+k3t9n3E2faFejxCO+aduNeqY0tooloo0y0mYn4qtJRTip/mt7uI+KuUI+TqO2skp+QmmRoVKp3zSsMAZtLOcY9Ysjkd7195aKCzIAwnSyc8x0EaMHFO+7G668nzSXbLldR3jFv5N0/EO0vudgivLlD30oKTIJM3uVwug+BrZgBzYj47ENJ5n4v5rpXGUIAVuxLpb2Ogte+2os/qpP7Arw2+k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
