travis:
  secure:
    BINSTAR_TOKEN: RkMHjYiTsvnk27i4pU0w9LK9AS6FRXTiyGv2h2x5bkkXgkFclr9a24nSQMQs3atNR3i7C8wV7baiXNH4/zo387XeLKz2Vhcfcd9pzelCepVDQgThcQSWQQFpFTjzQCehK81UIBsTSOaIYUzyIDRat0hcEAPm/Vwz0/7nmKsXSDWWmEGliWcSNyiAvsvaDD7iHqI4QLpPRwAfX1fOdPOhWrvgSssEgMz7LRQSYTaaHSqmSIh3uy8WPpvRpnOagtHR+Qzy9g8zet0iHL1INV5bd0OEbBqZcR3AliVAgW2W3QDmADicckazUT83hNsqFaQuaMjn5b2pvnzmRuaRY2oSE67tlrzCYBRKgJLWL4pU9cZ+dRghLjRIuOJAb9dhS6BPEofDOdyYne8Sc5AAoz8XJGLZdMQ9qFW8QmcUIFPoWqXUBpMsfOLC+9D5Y1yZf327acTvlCIe9zAYdN294SgBd9B/SsPaw19CwNo/slFRETjZPO35zLho7oOmovjuT8WX4Adf9Med4Gtf9LfipKxXjz+TlBkK5mPHmPsSlWk83vpzOIrVOLqbVicnTWDVYGBxP88GOhfLvB+vXyUORjk6SfFv3v/tTahA+IU3YRM0UyCtXqUnvSsvettZ+8C9ohR7+5Vl8JeQIJLP4zOpxhSfp2DZRs7GuUagf73iz7g6KcQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
